- internal/aws/client.go
- internal/aws/client_test.go
- internal/aws/users.go
- internal/aws/users_test.go
- internal/sync.go
*Issue #8 
This PR add the functionality to synchronise the Active/Disabled State for a user between Gsuite and AWS SSO.
It contains added logic and a new function UpdateUser.
> feat: Added functionality to sync and update the disabled status for a user

- internal/sync.go
*Issue #10
When there are deleted users in Gsuite that are previous synced to AWS SSO the logic stops the whole syncUsers loop
The current loop is:
```
uu, err := s.aws.FindUserByEmail(u.PrimaryEmail)
if err != aws.ErrUserNotFound  {
```
However aws.FindUserByEmail
return aws.ErrUserNotFound when a user is not found and nil when a user is found.
Replaced with:
```
if err != aws.ErrUserNotFound && err != nil {
```
and added extra logging around deleting users.
> fix: Sync Users loop stops when there is a deleted user

- README.md
- cmd/root.go
- internal/config/config.go
- internal/sync.go
Adding the option to *only* include a specified groups to the sync operation.
> feat(include-group): adding include-groups option

- .github/workflows/main.yml
- template.yaml
*Issue #, if available:* - 
Changing Function policy to limit access to the secrets we create.
Without this, the function has access to every secret, this policy should scope if to the proper resources.
> fix: limit iam policy only to the secret arns

- template.yaml
N/A
mask the parameter value to prevent it from being displayed in the console, command line tools, or API
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#parameters-section-structure-properties
> improv: set NoEcho on sensitive params in template.yaml

- internal/sync.go
The existing flow to ignore group is not working properly.
In detail:
`s.google.GetGroups` will return list of groups
`s.getGoogleGroupsAndUsers` will return the list of user from group which not filtered by flag `--ignore-groups`
up until this step is correct. next step will make it break.
`getGroupOperations` will return list of groups that need to be created in AWS SSO. This function do not have filter. It will cause the group that supposed to be ignored get created.
The fix is to filter output of `s.google.GetGroups` by value from flag `--ignore-groups`
Therefore the remaining flow will have certainty that no ignored group get processed.
*Example*
Execution
```
go run main.go \
-t $SSO_TOKEN \
-d \
-e $SSO_ENDPOINT\
-u …
```
> fix --ignore-groups flag to ignore group from google group

- Makefile
An additional `--s3-bucket` on the  package command is redundant.  There is no way to pass the s3 prefix to the package command.
Removes the extra `--s3-bucket` and instead replaces with `--s3-prefix`, passing in the environment variable.
> Replaces extra `--s3-bucket` with `--s3-prefix`

- internal/google/client.go
*Issue #56*
Error:
`
[{"path":"github.com/aws/aws-lambda-go@v1.23.0/lambda/errors.go","line":39,"label":"lambdaPanicResponse"},{"path":"github.com/aws/aws-lambda-go@v1.23.0/lambda/function.go","line":36,"label":"(*Function).Invoke.func1"},{"path":"runtime/panic.go","line":965,"label":"gopanic"},{"path":"runtime/panic.go","line":212,"label":"panicmem"},{"path":"runtime/signal_unix.go","line":734,"label":"sigpanic"},{"path":"cfir/git/ssosync/internal/google/client.go","line":45,"label":"NewClient"},{"path":"cfir/git/ssosync/internal/sync.go","line":687,"label":"DoSync"},{"path":"cfir/git/ssosync/cmd/root.go","line":55,"label":"glob..func1"},{"path":"github.com/spf13/cobra@v1.1.3/command.go","line":852,"label":"(*Command).execute"},{"path":"github.com/spf13/cobra@v1. …
> Google client err handling improvement

- internal/sync.go
Closes #76 
Just ignores and alerts when a user listed as a member group doesn't exist.
> fix: Ignore missing user in group members

- template.yaml
Add identityStore:DeleteGroup IAM permission
This action is performed during the sync:
https://github.com/awslabs/ssosync/blob/955e8e23a42340d323e25659c8c03130b5609c80/internal/sync.go#L511
But the template does not give the IAM role permission to delete groups:
https://github.com/awslabs/ssosync/blob/b4352b919996c0dfd4fad03c0e7a8000e5fd5f88/template.yaml#L164
Resolves #116.
> Add identityStore:DeleteGroup IAM permission

- internal/aws/client.go
- internal/sync.go
Since AWS SSO SCIM only supports [fetching up to 50 users in the ListUsers request](https://docs.aws.amazon.com/singlesignon/latest/developerguide/listusers.html#not-supported-listusers), we must ignore the case when the API returns the HTTP Code 409 (Conflict), that indicated the resource already exists.
Fixes #65
> fix: A case where the user already exists but it tries to create again

- README.md
Users need to define also the `S3_PREFIX` variable if they want to upload the files with `make package`. 
Add this missing information to README.md.
> Add missing environment variable  to README

- template.yaml
*Issue #, if available:* A quick and easy workaround for those experiencing #17
Allow the Timeout value of the Lambda function to be modified via the SAM Application/CloudFormation template. We've recently sailed past the default 5 minute limit, and this change would make our IaC simpler.
> Make the Lambda timeout setting user configurable

- template.yaml
This changes the instances of the [NoValue pseudo-parameter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html) to use the [Ref intrinsic function](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html), so that the key is omitted instead of the literal string `AWS::NoValue` being used.
Without this change, attempting to deploy the stack without a specified FunctionName results in an error:
```
Resource handler returned message: "1 validation error detected: Value 'AWS::NoValue' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:(aws[a-zA-Z-]*)?:lambda:)?([a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a- …
```
> Change NoValue psuedo-parameters to references

- template.yaml
*Issue #, if available:* #162
Added an escape to the character class usage of the hyphen character in the CloudFormation template. 
> Escape hyphens in user/group character classes

- internal/sync.go
Added additional connection tests for each service required.
> Bugfix improve connection test

- cmd/root.go
Addresses env Vars not being pulled into the executable when running under Lambda.
> Bugfix env vars

- internal/sync.go
Logic for flattening nested groups was flawed.
- Added group detail caching, to reduce api calls
- function for handling group memberships, redesigned for recursion to efficiently handle any depth of nesting.
> Fix nested groups

- cicd/account_execution/staging/buildspec.yml
- internal/sync.go
#199 199
Add de-dupe block, to get group members function. 
> 199 group flattening can lead to conflicts due to non uniqueness

- internal/google/client.go
#194 
When the google api appears to return zero groups or users, then an error is thrown to terminate execution.
> 194 sso lambda deletes then recreates users

- internal/aws/users.go
- internal/google/client.go
- internal/sync.go
#200 
Google directory will accept a 'zero width space' for an empty name but will not accept a 'space', conversely AWS IAM Identity Store will accept a 'space' for an empty name but not a 'zero width space'. This change replaces 'zero width space' characters with a 'space' in the name fields of users fetched from the Google directory.
> 200 name handling

- template.yaml
#206
Updated the CloudFormation template to hardcode the maximum allowed concurrency for the lambda function to 1. There is no situation under which it would be safe to run more than one instance. 
> Restrict Maximum Concurrency for the ssosync lambda to 1

- cmd/root.go
- internal/aws/client.go
- internal/aws/client_test.go
- internal/aws/http.go
- internal/aws/mock/mock_http.go
- internal/config/secrets.go
- internal/google/client.go
- internal/sync.go
- internal/sync_test.go
> Fixes for workflow automations

- template.yaml
webUi now provides the url without the trailing '/' making this optional for backward and forward compatibility.
#222 
Updated the scim endpoint regex, since the change in webUi now on longer has a trailing '/' on the url provided.
> SCIM url regex

- .gitignore
- cicd/build/package/buildspec.yml
- cicd/cloudformation/secrets.yaml
- template.yaml
#224 224
Updated regexes in the SAR template and CICD pipeline templates.
> 224 scimendpointurl with anoother pattern

- cmd/root.go
- go.mod
- internal/config/config.go
- internal/google/client.go
- internal/sync.go
- template.yaml
#248 
Add template option to configure the RAM allocation for the lambda function, retains default of 128MB.
Allows Precaching queries to be customized from the full directory scope,
Specify _OrgUnitPath_ if User is not found in the precache then its added on the fly
Precaching can be disabled entirely by specifying **DISABLED**
If an invalid query is supplied sync will continue but as though precaching was disabled
> Add configuration options: RAM allocation (default to 128MB), Precaching

- go.mod
Given nix derivation:
```nix
ssosync = pkgs.buildGoModule rec {
pname = "ssosync";
version = "3a096fb5b8d1db83ebf07ef2cc3871c9bb185c73";
src = pkgs.fetchFromGitHub {
owner = "ethonAI";
repo = "ssosync";
rev = version;
hash = "sha256-i4L3fDMfHwX0ExR1jrV+sAm7Hx5tZuA2EapZHbyyF00=";
};
vendorHash = "sha256-7px6+K+2byltj58l3vsK2FFAtslZvgLbZ9slfbJf9Uk=";
};
```
**without** the proposed changes the following error is encountered:
```
vendor/golang.org/x/sys/unix/syscall.go:82:16: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
vendor/golang.org/x/sys/unix/syscall_bsd.go:247:20: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)
vendor/golang.org/x/sys/unix/syscall_darwin.go:94:8: unsafe.Slice requires go1.17 or later (-lang was set to …
```
> Bump dependencies to allow nix builds

- internal/google/client.go
- internal/sync.go
- template.yaml
#268, #261
Added additional checks to catch, when google ADK returns empty set of groups.
Added additional checks to group membership, to filter out none user members.
Update execution order for apply changes to AWS side, to avoid resource not found issues.
> Bug Fix : Release v2.3.3
